version: '3'


services:
  nginx:
    image: nginx:latest
    env_file:
      - ./env/gamification.env
    volumes:
      - ./env/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      - web
    ports:
      - 8000:8000
    restart: always

  web:
    build: .
    image: gamification:latest
    env_file:
      - env/gamification.env
      - env/db.env
    depends_on:
      - db
    command: ['./runserver.sh']
    restart: always

  db:
    image: postgres:9.6
    env_file: env/db.env
    volumes:
      - ./srv/postgres-data:/var/lib/postgresql/data/
    privileged: true
    restart: always

  judge0-server:
    image: judge0/api:1.9.0
    volumes:
      - ./env/judge0.env:/judge0.conf:ro
    privileged: true
    depends_on:
      - judge0-db
      - judge0-redis
    restart: always

  judge0-workers:
    image: judge0/api:1.9.0
    command: ["./scripts/workers"]
    volumes:
      - ./env/judge0.env:/judge0.conf:ro
    privileged: true
    depends_on:
      - judge0-db
      - judge0-redis
    restart: always

  judge0-db:
    image: postgres:9.6
    env_file: env/judge0.env
    volumes:
      - ./srv/judge0-postgres-data:/var/lib/postgresql/data/
    privileged: true
    restart: always

  judge0-redis:
    image: redis:4.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: env/judge0.env
    volumes:
      - ./srv/redis-data:/data
    restart: always
  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres # Optional: see below
    volumes:
      - ./srv/pgbackups:/backups
    links:
      - db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourPasswordHere1234
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080