version: '3'


services:
  nginx:
    image: nginx:latest
    volumes:
      - ./env/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      - web
    ports:
      - 80:80

  web:
    build: .
    image: gamification:latest
    env_file:
      - env/gamification.env
      - env/db.env
    depends_on:
      - db
    command: ['./runserver.sh']

  db:
    image: postgres:9.6
    env_file: env/db.env
    volumes:
      - ./srv/postgres-data:/var/lib/postgresql/data/
    privileged: true
    restart: always

  judge0-server:
    image: judge0/api:1.9.0-extra
    volumes:
      - ./env/judge0.env:/judge0.conf:ro
    privileged: true
    depends_on:
      - judge0-db
      - judge0-redis
    restart: always

  judge0-workers:
    image: judge0/api:1.9.0-extra
    command: ["./scripts/workers"]
    volumes:
      - ./env/judge0.env:/judge0.conf:ro
    privileged: true
    depends_on:
      - judge0-db
      - judge0-redis
    restart: always

  judge0-db:
    image: postgres:9.6
    env_file: env/judge0.env
    volumes:
      - ./srv/judge0-postgres-data:/var/lib/postgresql/data/
    privileged: true
    restart: always

  judge0-redis:
    image: redis:4.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: env/judge0.env
    volumes:
      - ./srv/redis-data:/data
    restart: always