# Generated by Django 3.0.1 on 2020-02-17 07:35

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text', djrichtextfield.models.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='VariableQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course.Question')),
                ('variables', jsonfield.fields.JSONField(default=dict)),
            ],
            bases=('course.question',),
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('variablequestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course.VariableQuestion')),
                ('choices', jsonfield.fields.JSONField(default=dict)),
            ],
            bases=('course.variablequestion',),
        ),
    ]
