# Generated by Django 3.0.3 on 2020-06-26 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsonsquestion',
            name='results',
        ),
        migrations.RemoveField(
            model_name='parsonsquestion',
            name='tokens',
        ),
    ]
