# Generated by Django 3.0.7 on 2020-08-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionjunction',
            name='opened_question',
        ),
        migrations.AddField(
            model_name='userquestionjunction',
            name='last_viewed',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
