# Generated by Django 3.0.3 on 2020-03-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='javasubmission',
            name='code',
        ),
        migrations.RemoveField(
            model_name='multiplechoicesubmission',
            name='answer',
        ),
        migrations.AddField(
            model_name='submission',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_partially_correct',
            field=models.BooleanField(default=False),
        ),
    ]
