# Generated by Django 3.0.3 on 2020-07-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_submission_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsonsquestion',
            name='additional_file_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
