# Generated by Django 3.0.7 on 2020-08-15 07:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_auto_20200814_2314'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userquestionjunction',
            unique_together={('user', 'question')},
        ),
    ]
