# Generated by Django 3.0.3 on 2020-04-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200316_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_submission_allowed',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
