# Generated by Django 3.0.3 on 2020-08-01 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_parsonsquestion_additional_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='code',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='question',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.AddField(
            model_name='submission',
            name='uqj',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='course.UserQuestionJunction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userquestionjunction',
            name='is_partially_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userquestionjunction',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
