# Generated by Django 3.0.3 on 2020-05-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200505_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenvalue',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'EASY'), ('NORMAL', 'NORMAL'), ('HARD', 'HARD')], default='EASY', max_length=100),
        ),
    ]
