# Generated by Django 3.0.3 on 2020-02-17 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('course', '0005_auto_20200217_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiplechoicequestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='variablequestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='question',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_course.question_set+', to='contenttypes.ContentType'),
        ),
    ]
