# Generated by Django 3.0.7 on 2020-08-10 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_userquestionjunction_random_seed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='javaquestion',
            name='question_ptr',
        ),
        migrations.AddField(
            model_name='javaquestion',
            name='variablequestion_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course.VariableQuestion'),
            preserve_default=False,
        ),
    ]
