# Generated by Django 3.0.3 on 2020-02-18 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200217_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='object_id',
        ),
        migrations.AddField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='course.Question'),
            preserve_default=False,
        ),
    ]
