# Generated by Django 3.0.7 on 2020-10-02 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0005_canvascourse_mock'),
        ('course', '0006_auto_20200921_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_set', to='canvas.CanvasCourse'),
        ),
        migrations.AlterField(
            model_name='question',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_set', to='canvas.Event'),
        ),
    ]
