# Generated by Django 3.0.3 on 2020-05-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_questioncategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='visible_distractor_count',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
