# Generated by Django 3.0.3 on 2020-06-21 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_multiplechoicequestion_visible_distractor_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'EASY'), ('NORMAL', 'MEDIUM'), ('HARD', 'HARD')], default='EASY', max_length=100),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.QuestionCategory'),
        ),
        migrations.AlterField(
            model_name='tokenvalue',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'EASY'), ('NORMAL', 'MEDIUM'), ('HARD', 'HARD')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tokenvalue',
            name='value',
            field=models.FloatField(),
        ),
    ]
