# Generated by Django 3.0.3 on 2020-02-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20200217_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
