# Generated by Django 3.0.7 on 2020-11-18 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_question_is_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='before', to='course.QuestionCategory'),
        ),
    ]
