# Generated by Django 3.0.3 on 2020-02-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_submission_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('VERY EASY', 'VERY EASY'), ('EASY', 'EASY'), ('NORMAL', 'NORMAL'), ('HARD', 'HARD'), ('VERY HARD', 'VERY HARD')], default='HARD', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='token_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
