# Generated by Django 3.0.3 on 2020-06-21 01:03

import course.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20200620_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javaquestion',
            name='test_cases',
            field=course.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='javasubmission',
            name='results',
            field=course.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='javasubmission',
            name='tokens',
            field=course.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='choices',
            field=course.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='variablequestion',
            name='variables',
            field=course.fields.JSONField(default=dict),
        ),
    ]
