# Generated by Django 3.0.7 on 2020-12-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20201120_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='next_categories',
            field=models.ManyToManyField(blank=True, related_name='prev_categories', to='course.QuestionCategory'),
        ),
    ]
