# Generated by Django 3.0.3 on 2020-03-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20200226_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
