# Generated by Django 3.0.7 on 2020-11-25 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_questioncategory_next_categories'),
        ('course', '0009_auto_20201120_1808'),
    ]

    operations = [
    ]
