# Generated by Django 3.0.7 on 2020-11-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_questioncategory_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncategory',
            name='link',
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='link',
            field=models.ManyToManyField(related_name='_questioncategory_link_+', to='course.QuestionCategory'),
        ),
    ]
