# Generated by Django 3.0.3 on 2020-03-08 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_question_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxQuestion',
            fields=[
                ('multiplechoicequestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course.MultipleChoiceQuestion')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('course.multiplechoicequestion',),
        ),
    ]
