# Generated by Django 3.0.7 on 2020-11-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20201118_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncategory',
            name='link',
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='links_to',
            field=models.ManyToManyField(related_name='_questioncategory_links_to_+', to='course.QuestionCategory'),
        ),
    ]
