# Generated by Django 3.0.3 on 2020-03-14 21:31

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_checkboxquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='JavaQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course.Question')),
                ('test_cases', jsonfield.fields.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('course.question',),
        ),
    ]
