# Generated by Django 3.0.14 on 2021-06-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20210420_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='is_checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
