# Generated by Django 3.0.14 on 2021-06-06 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20210420_2257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckboxQuestion',
        ),
    ]
