# Generated by Django 3.0.3 on 2020-03-14 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0012_javaquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='JavaSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('tokens', jsonfield.fields.JSONField(default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='java_submissions', to='course.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='java_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
