# Generated by Django 3.0.14 on 2021-06-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='tokens',
            field=models.IntegerField(default=0),
        ),
    ]
