# Generated by Django 3.0.14 on 2021-07-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_delete_checkboxquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_status',
            field=models.CharField(choices=[('CRE', 'CREATED'), ('DEL', 'DELETED')], default='CRE', max_length=3, null=True),
        ),
    ]
