# Generated by Django 3.0.14 on 2021-07-04 23:27

import course.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_delete_checkboxquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsonsquestion',
            name='input_files',
            field=course.fields.JSONField(default=[]),
        ),
    ]
