# Generated by Django 3.0.14 on 2021-06-03 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_multiplechoicequestion_is_checkbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='is_checkbox',
        ),
    ]
