# Generated by Django 3.0.3 on 2020-03-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_javasubmission_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='javasubmission',
            name='grade',
            field=models.FloatField(default=0),
        ),
    ]
