# Generated by Django 3.0.14 on 2021-06-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_testmodel_tokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='user',
            new_name='username',
        ),
    ]
