# Generated by Django 3.0.14 on 2021-06-26 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_delete_checkboxquestion'),
        ('course', '0015_auto_20210617_1132'),
    ]

    operations = [
    ]
