# Generated by Django 3.0.14 on 2021-07-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0015_auto_20210704_1627"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parsonsquestion",
            name="additional_file_name",
        ),
        migrations.RemoveField(
            model_name="parsonsquestion",
            name="lines",
        ),
        migrations.AddField(
            model_name="parsonssubmission",
            name="answer_files",
            field=models.JSONField(default=dict),
        ),
    ]
