# Generated by Django 3.0.3 on 2020-03-16 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_javasubmission_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='token_value',
        ),
        migrations.CreateModel(
            name='TokenValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('difficulty', models.CharField(choices=[('VERY EASY', 'VERY EASY'), ('EASY', 'EASY'), ('NORMAL', 'NORMAL'), ('HARD', 'HARD'), ('VERY HARD', 'VERY HARD')], max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_values', to='course.QuestionCategory')),
            ],
            options={
                'unique_together': {('category', 'difficulty')},
            },
        ),
    ]
