# Generated by Django 3.0.14 on 2021-06-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20210625_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='coldStreak',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='hotStreak',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
