# Generated by Django 3.0.14 on 2021-07-18 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_auto_20210717_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='javaquestion',
            name='input_file_names',
        ),
    ]
