# Generated by Django 3.0.14 on 2021-06-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_auto_20210626_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='team',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
