# Generated by Django 3.0.14 on 2021-07-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('course', '0014_question_question_status'),
        ('course', '0019_remove_javaquestion_input_file_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('DELETED', 'DELETED')], default='CREATED',
                                   max_length=10, null=True),
        ),
    ]
