# Generated by Django 3.0.14 on 2021-10-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_question_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionjunction',
            name='is_favourite',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
