# Generated by Django 3.0.14 on 2021-07-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_auto_20210704_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='is_visible',
        ),
    ]
