# Generated by Django 3.0.14 on 2021-07-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_remove_leaderboard_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardstudents',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboardstudents',
            name='team',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
