# Generated by Django 3.0.14 on 2021-10-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_reportquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportquestion',
            name='report_text',
            field=models.TextField(db_index=True, default=False),
        ),
    ]
