# Generated by Django 3.0.14 on 2021-07-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_auto_20210704_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
