# Generated by Django 3.0.14 on 2021-10-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_reportquestion_report_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportquestion',
            old_name='is_report',
            new_name='language_specific_issue',
        ),
        migrations.AddField(
            model_name='reportquestion',
            name='other',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='reportquestion',
            name='poor_test_coverage',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='reportquestion',
            name='test_case_incorrect_answer',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='reportquestion',
            name='test_case_violate_constraints',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='reportquestion',
            name='unclear_description',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
