# Generated by Django 3.0.14 on 2022-12-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0024_auto_20211203_1955"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestionjunction",
            name="solved_at",
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="userquestionjunction",
            name="last_viewed",
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
