# Generated by Django 3.0.14 on 2021-07-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_auto_20210704_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='assigned_course',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leaderboardstudents',
            name='leader_board',
        ),
        migrations.RemoveField(
            model_name='leaderboardstudents',
            name='student',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.DeleteModel(
            name='LeaderBoard',
        ),
        migrations.DeleteModel(
            name='LeaderBoardStudents',
        ),
    ]
