# Generated by Django 3.0.14 on 2021-08-04 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_auto_20210719_2232'),
        ('course', '0020_question_question_status'),
    ]

    operations = [
    ]
