# Generated by Django 3.0.14 on 2021-07-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_question_question_status'),
        ('course', '0025_auto_20210719_2232'),
    ]

    operations = [
    ]
