# Generated by Django 3.0.14 on 2023-04-15 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0026_auto_20230414_1217"),
        ("course", "0025_auto_20221215_1340"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_set",
                to="canvas.CanvasCourse",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_set",
                to="canvas.Event",
            ),
        ),
    ]
