# Generated by Django 3.0.14 on 2023-09-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0026_auto_20230415_1430"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestionjunction",
            name="grade",
            field=models.FloatField(default=0),
        ),
    ]
