# Generated by Django 3.0.14 on 2021-08-05 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_merge_20210730_1419'),
        ('course', '0026_merge_20210803_1824'),
    ]

    operations = [
    ]
