# Generated by Django 3.0.14 on 2024-02-19 21:34

import course.models.models
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0027_userquestionjunction_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="variablequestion",
            name="variation_types",
            field=jsonfield.fields.JSONField(
                default=[], validators=[course.models.models.validate_variation_type_json]
            ),
        ),
    ]
