# Generated by Django 6.0.7 on 2026-08-03 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("course", "0028_variablequestion_variation_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codesubmission",
            options={},
        ),
        migrations.AlterModelOptions(
            name="javaquestion",
            options={},
        ),
        migrations.AlterModelOptions(
            name="javasubmission",
            options={},
        ),
        migrations.AlterModelOptions(
            name="multiplechoicequestion",
            options={},
        ),
        migrations.AlterModelOptions(
            name="multiplechoicesubmission",
            options={},
        ),
        migrations.AlterModelOptions(
            name="parsonsquestion",
            options={},
        ),
        migrations.AlterModelOptions(
            name="parsonssubmission",
            options={},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={},
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={},
        ),
        migrations.AlterModelOptions(
            name="variablequestion",
            options={},
        ),
        migrations.AlterField(
            model_name="question",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
