# Generated by Django 3.0.14 on 2022-02-03 06:26

import course.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0026_remove_submission_time_spent'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('canvas', '0011_merge_20211116_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(default='n/a', max_length=255)),
                ('last_name', models.CharField(default='n/a', max_length=255)),
                ('num_attempts', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_spent', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.Event')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_analytics.submissionanalytics_set+', to='contenttypes.ContentType')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Submission')),
                ('uqj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.UserQuestionJunction')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='JavaSubmissionAnalytics',
            fields=[
                ('submissionanalytics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.SubmissionAnalytics')),
                ('lines', models.IntegerField(default=0)),
                ('blank_lines', models.IntegerField(default=0)),
                ('comment_lines', models.IntegerField(default=0)),
                ('import_lines', models.IntegerField(default=0)),
                ('cyclomatic_complexity', models.IntegerField(default=0)),
                ('method', models.IntegerField(default=0)),
                ('operator', models.IntegerField(default=0)),
                ('operand', models.IntegerField(default=0)),
                ('unique_operator', models.IntegerField(default=0)),
                ('unique_operand', models.IntegerField(default=0)),
                ('vocab', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('vol', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('difficulty', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('effort', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('error', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('test_time', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('ans_file', course.fields.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('analytics.submissionanalytics',),
        ),
        migrations.CreateModel(
            name='MCQSubmissionAnalytics',
            fields=[
                ('submissionanalytics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.SubmissionAnalytics')),
                ('answer', models.CharField(default='n/a', max_length=5)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('analytics.submissionanalytics',),
        ),
        migrations.CreateModel(
            name='ParsonsSubmissionAnalytics',
            fields=[
                ('submissionanalytics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.SubmissionAnalytics')),
                ('lines', models.IntegerField(default=0)),
                ('blank_lines', models.IntegerField(default=0)),
                ('comment_lines', models.IntegerField(default=0)),
                ('import_lines', models.IntegerField(default=0)),
                ('cyclomatic_complexity', models.IntegerField(default=0)),
                ('method', models.IntegerField(default=0)),
                ('operator', models.IntegerField(default=0)),
                ('operand', models.IntegerField(default=0)),
                ('unique_operator', models.IntegerField(default=0)),
                ('unique_operand', models.IntegerField(default=0)),
                ('vocab', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('vol', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('difficulty', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('effort', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('error', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('test_time', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('ans_file', course.fields.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('analytics.submissionanalytics',),
        ),
    ]
