# Generated by Django 3.0.14 on 2021-12-07 05:33

import course.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.IntegerField(default=0)),
                ('event', models.IntegerField(default=0)),
                ('number_submission', models.IntegerField(default=0)),
                ('avg_grade', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('correct_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('frequently_wrong_ans', models.CharField(default='n/a', max_length=5)),
                ('frequently_wrong_reason', models.CharField(default='n/a', max_length=255)),
                ('lines', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('blank_lines', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('comment_lines', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('import_lines', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cc', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('method', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('operator', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('operand', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('unique_operator', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('unique_operand', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('vocab', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('size', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('vol', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('difficulty', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('effort', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('error', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('test_time', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uqj', models.IntegerField(default=0)),
                ('submission', models.IntegerField(default=0)),
                ('question', models.IntegerField(default=0)),
                ('event', models.IntegerField(default=0)),
                ('first_name', models.CharField(default='n/a', max_length=255)),
                ('last_name', models.CharField(default='n/a', max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JavaSubmissionAnalytics',
            fields=[
                ('submissionanalytics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.SubmissionAnalytics')),
                ('lines', models.IntegerField(default=0)),
                ('blank_lines', models.IntegerField(default=0)),
                ('comment_lines', models.IntegerField(default=0)),
                ('import_lines', models.IntegerField(default=0)),
                ('cc', models.IntegerField(default=0)),
                ('method', models.IntegerField(default=0)),
                ('operator', models.IntegerField(default=0)),
                ('operand', models.IntegerField(default=0)),
                ('unique_operator', models.IntegerField(default=0)),
                ('unique_operand', models.IntegerField(default=0)),
                ('vocab', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('vol', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('difficulty', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('effort', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('error', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('test_time', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('ans_file', course.fields.JSONField(default=dict)),
            ],
            bases=('analytics.submissionanalytics',),
        ),
        migrations.CreateModel(
            name='MCQSubmissionAnalytics',
            fields=[
                ('submissionanalytics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.SubmissionAnalytics')),
                ('answer', models.CharField(default='n/a', max_length=5)),
            ],
            bases=('analytics.submissionanalytics',),
        ),
        migrations.CreateModel(
            name='ParsonsSubmissionAnalytics',
            fields=[
                ('submissionanalytics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.SubmissionAnalytics')),
                ('lines', models.IntegerField(default=0)),
                ('blank_lines', models.IntegerField(default=0)),
                ('comment_lines', models.IntegerField(default=0)),
                ('import_lines', models.IntegerField(default=0)),
                ('cc', models.IntegerField(default=0)),
                ('method', models.IntegerField(default=0)),
                ('operator', models.IntegerField(default=0)),
                ('operand', models.IntegerField(default=0)),
                ('unique_operator', models.IntegerField(default=0)),
                ('unique_operand', models.IntegerField(default=0)),
                ('vocab', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('vol', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('difficulty', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('effort', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('error', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('test_time', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('ans_file', course.fields.JSONField(default=dict)),
            ],
            bases=('analytics.submissionanalytics',),
        ),
    ]
