# Generated by Django 3.0.14 on 2022-01-24 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('analytics', '0002_submissionanalytics_time_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='javasubmissionanalytics',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='mcqsubmissionanalytics',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='parsonssubmissionanalytics',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='submissionanalytics',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='submissionanalytics',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_analytics.submissionanalytics_set+', to='contenttypes.ContentType'),
        ),
    ]
