# Generated by Django 3.0.14 on 2022-01-24 20:01

import course.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_remove_submission_time_spent'),
        ('canvas', '0011_merge_20211116_1744'),
        ('analytics', '0003_auto_20220123_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('most_frequent_wrong_ans', course.fields.JSONField(default=dict)),
                ('avg_grade', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grade_std_dev', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('num_respondents', models.IntegerField(default=0)),
                ('avg_attempt', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('attempt_std_dev', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('median_time_spent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.CanvasCourse')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.Event')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Question')),
            ],
        ),
        migrations.CreateModel(
            name='JavaQuestionAnalytics',
            fields=[
                ('questionanalytics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.QuestionAnalytics')),
                ('lines', models.IntegerField(default=0)),
                ('blank_lines', models.IntegerField(default=0)),
                ('comment_lines', models.IntegerField(default=0)),
                ('import_lines', models.IntegerField(default=0)),
                ('cc', models.IntegerField(default=0)),
                ('method', models.IntegerField(default=0)),
                ('operator', models.IntegerField(default=0)),
                ('operand', models.IntegerField(default=0)),
                ('unique_operator', models.IntegerField(default=0)),
                ('unique_operand', models.IntegerField(default=0)),
                ('vocab', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('vol', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('difficulty', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('effort', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('error', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('test_time', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
            ],
            bases=('analytics.questionanalytics',),
        ),
        migrations.CreateModel(
            name='MCQQuestionAnalytics',
            fields=[
                ('questionanalytics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.QuestionAnalytics')),
            ],
            bases=('analytics.questionanalytics',),
        ),
        migrations.CreateModel(
            name='ParsonsQuestionAnalytics',
            fields=[
                ('questionanalytics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.QuestionAnalytics')),
                ('lines', models.IntegerField(default=0)),
                ('blank_lines', models.IntegerField(default=0)),
                ('comment_lines', models.IntegerField(default=0)),
                ('import_lines', models.IntegerField(default=0)),
                ('cc', models.IntegerField(default=0)),
                ('method', models.IntegerField(default=0)),
                ('operator', models.IntegerField(default=0)),
                ('operand', models.IntegerField(default=0)),
                ('unique_operator', models.IntegerField(default=0)),
                ('unique_operand', models.IntegerField(default=0)),
                ('vocab', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('vol', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('difficulty', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('effort', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('error', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('test_time', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
            ],
            bases=('analytics.questionanalytics',),
        ),
    ]
