# Generated by Django 3.0.14 on 2021-12-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20211206_2135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionAnalytics',
        ),
    ]
