# Generated by Django 3.0.14 on 2021-12-10 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_delete_questionanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.IntegerField(default=0)),
                ('event', models.IntegerField(default=0)),
                ('number_submission', models.IntegerField(default=0)),
                ('avg_grade', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('correct_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('frequently_wrong_ans', models.CharField(default='n/a', max_length=5)),
                ('frequently_wrong_reason', models.CharField(default='n/a', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JavaQuestionAnalytics',
            fields=[
                ('questionanalytics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.QuestionAnalytics')),
                ('lines', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('blank_lines', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('comment_lines', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('import_lines', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cc', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('method', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('operator', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('operand', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('unique_operator', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('unique_operand', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('vocab', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('size', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('vol', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('difficulty', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('effort', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('error', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('test_time', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            bases=('analytics.questionanalytics',),
        ),
        migrations.CreateModel(
            name='MCQQuestionAnalytics',
            fields=[
                ('questionanalytics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.QuestionAnalytics')),
            ],
            bases=('analytics.questionanalytics',),
        ),
        migrations.CreateModel(
            name='ParsonsQuestionAnalytics',
            fields=[
                ('questionanalytics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.QuestionAnalytics')),
                ('lines', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('blank_lines', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('comment_lines', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('import_lines', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cc', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('method', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('operator', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('operand', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('unique_operator', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('unique_operand', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('vocab', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('size', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('vol', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('difficulty', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('effort', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('error', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('test_time', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            bases=('analytics.questionanalytics',),
        ),
    ]
