# Generated by Django 3.0.14 on 2022-01-12 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_auto_20211203_1955'),
        ('canvas', '0011_merge_20211116_1744'),
        ('analytics', '0004_delete_questionanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionanalytics',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.Event'),
        ),
        migrations.AlterField(
            model_name='submissionanalytics',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Question'),
        ),
        migrations.AlterField(
            model_name='submissionanalytics',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Submission'),
        ),
        migrations.AlterField(
            model_name='submissionanalytics',
            name='uqj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.UserQuestionJunction'),
        ),
    ]
