# Generated by Django 3.0.14 on 2022-01-24 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0011_merge_20211116_1744'),
        ('analytics', '0004_javaquestionanalytics_mcqquestionanalytics_parsonsquestionanalytics_questionanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanalytics',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canvas.CanvasCourse'),
        ),
    ]
