# Generated by Django 3.0.14 on 2022-01-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20220111_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionanalytics',
            name='num_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submissionanalytics',
            name='success',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submissionanalytics',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
