# Generated by Django 3.0.14 on 2022-01-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20220124_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanalytics',
            name='avg_attempt',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
