# Generated by Django 3.0.14 on 2021-12-10 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20211209_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='javaquestionanalytics',
            options={},
        ),
        migrations.AlterModelOptions(
            name='javasubmissionanalytics',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mcqquestionanalytics',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mcqsubmissionanalytics',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parsonsquestionanalytics',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parsonssubmissionanalytics',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questionanalytics',
            options={},
        ),
        migrations.AlterModelOptions(
            name='submissionanalytics',
            options={},
        ),
        migrations.RemoveField(
            model_name='questionanalytics',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='submissionanalytics',
            name='polymorphic_ctype',
        ),
    ]
