# Generated by Django 3.0.14 on 2022-01-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20220111_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionanalytics',
            name='success',
        ),
        migrations.AddField(
            model_name='submissionanalytics',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
