# Generated by Django 3.0.14 on 2021-12-10 04:55

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    MyModel = apps.get_model('analytics', 'QuestionAnalytics')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    new_ct = ContentType.objects.get_for_model(MyModel)
    MyModel.objects.filter(polymorphic_ctype__isnull=True).update(polymorphic_ctype=new_ct)

def forwards_func1(apps, schema_editor):
    MyModel = apps.get_model('analytics', 'SubmissionAnalytics')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    new_ct = ContentType.objects.get_for_model(MyModel)
    MyModel.objects.filter(polymorphic_ctype__isnull=True).update(polymorphic_ctype=new_ct)


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('analytics', '0007_auto_20211209_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='javaquestionanalytics',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='javasubmissionanalytics',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='mcqquestionanalytics',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='mcqsubmissionanalytics',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='parsonsquestionanalytics',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='parsonssubmissionanalytics',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='questionanalytics',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='submissionanalytics',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='questionanalytics',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='polymorphic_analytics.questionanalytics_set+',
                                    to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='submissionanalytics',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='polymorphic_analytics.submissionanalytics_set+',
                                    to='contenttypes.ContentType'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.RunPython(forwards_func1, migrations.RunPython.noop),
    ]
