# Generated by Django 3.0.14 on 2021-12-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20211209_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanalytics',
            old_name='frequently_wrong_ans',
            new_name='frequent_wrong_ans',
        ),
        migrations.RenameField(
            model_name='questionanalytics',
            old_name='frequently_wrong_reason',
            new_name='frequent_wrong_reason',
        ),
    ]
