# Generated by Django 3.0.3 on 2020-03-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='tokens',
        ),
    ]
