# Generated by Django 3.0.3 on 2020-06-29 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200516_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='student_number',
        ),
    ]
