# Generated by Django 3.0.14 on 2021-06-09 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210420_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents', to=settings.AUTH_USER_MODEL),
        ),
    ]
