# Generated by Django 3.0.14 on 2023-09-20 21:30

from django.db import migrations, models
from django.db.models import F, Value
from django.db.models.functions import Concat


def forwards_func(apps, schema_editor):
    my_user = apps.get_model("accounts", "MyUser")
    my_user.objects.update(nickname=Concat(F("first_name"), Value(" "), F("last_name")))


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_auto_20220919_1956"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="nickname",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RunPython(forwards_func),
    ]
