# Generated by Django 3.0.14 on 2023-09-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_auto_20220919_1956"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="nickname",
            field=models.CharField(blank=True, max_length=30, verbose_name="nickname"),
        ),
        migrations.AddField(
            model_name="userconsent",
            name="nickname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
