# Generated by Django 3.0.14 on 2021-08-26 00:47

import canvas.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mock', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('course_id', models.IntegerField()),
                ('token', models.CharField(max_length=500)),
                ('allow_registration', models.BooleanField(default=False)),
                ('visible_to_students', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('verification_assignment_group_name', models.CharField(max_length=100)),
                ('verification_assignment_group_id', models.IntegerField(blank=True, null=True)),
                ('verification_assignment_name', models.CharField(max_length=100)),
                ('verification_assignment_id', models.IntegerField(blank=True, null=True)),
                ('bonus_assignment_group_name', models.CharField(max_length=100)),
                ('bonus_assignment_group_id', models.IntegerField(blank=True, null=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.CanvasCourse')),
            ],
            options={
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TokenUseOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_required', models.FloatField()),
                ('points_given', models.IntegerField()),
                ('maximum_number_of_use', models.IntegerField(default=1)),
                ('assignment_name', models.CharField(max_length=100)),
                ('assignment_id', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_use_options', to='canvas.CanvasCourse')),
            ],
        ),
        migrations.CreateModel(
            name='TokenUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_used', models.IntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_uses', to='canvas.TokenUseOption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_uses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('ASSIGNMENT', 'ASSIGNMENT'), ('EXAM', 'EXAM')], max_length=500)),
                ('count_for_tokens', models.BooleanField()),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='canvas.CanvasCourse')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canvas.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CanvasCourseRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_user_id', models.IntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_blocked', models.BooleanField(db_index=True, default=False)),
                ('verification_code', models.IntegerField(default=canvas.models.random_verification_code)),
                ('verification_attempts', models.IntegerField(default=3)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.CanvasCourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('course', 'user')},
            },
        ),
    ]
