# Generated by Django 3.0.7 on 2020-08-23 04:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='canvascourseregistration',
            unique_together={('course', 'user')},
        ),
    ]
