# Generated by Django 3.0.7 on 2020-09-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0004_auto_20200904_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvascourse',
            name='mock',
            field=models.BooleanField(default=False),
        ),
    ]
