# Generated by Django 3.0.14 on 2021-07-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0008_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvascourse',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
