# Generated by Django 3.0.14 on 2021-07-30 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0009_auto_20210702_1305'),
        ('canvas', '0009_auto_20210704_0428'),
    ]

    operations = [
    ]
