# Generated by Django 3.0.14 on 2021-10-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0009_auto_20210702_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvascourseregistration',
            name='registration_type',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('TA', 'TA'), ('INSTRUCTOR', 'INSTRUCTOR')], default='STUDENT', max_length=10, null=True),
        ),
    ]
