# Generated by Django 3.0.14 on 2021-11-17 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0010_canvascourseregistration_registration_type'),
        ('canvas', '0010_auto_20211025_1714'),
    ]

    operations = [
    ]
