# Generated by Django 3.0.14 on 2022-10-23 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0024_auto_20211203_1955"),
        ("canvas", "0014_goal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goal",
            name="category",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="initial_solved",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="number_of_questions",
        ),
        migrations.CreateModel(
            name="GoalItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[("EASY", "Easy"), ("MEDIUM", "Medium"), ("HARD", "Hard")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("initial_solved", models.IntegerField(blank=True)),
                ("number_of_questions", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_items",
                        to="course.QuestionCategory",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="goal_items", to="canvas.Goal"
                    ),
                ),
            ],
        ),
    ]
