# Generated by Django 3.0.14 on 2022-10-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0016_canvascourse_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="canvascourse",
            name="registration_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="canvascourse",
            name="registration_mode",
            field=models.CharField(choices=[("OPEN", "OPEN"), ("CODE", "CODE")], default="OPEN", max_length=100),
        ),
    ]
