# Generated by Django 3.0.14 on 2022-12-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0017_auto_20221029_1402"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="claimed",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
