# Generated by Django 3.0.14 on 2022-12-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0018_goal_claimed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="canvascourse",
            name="bonus_assignment_group_id",
        ),
        migrations.RemoveField(
            model_name="canvascourse",
            name="bonus_assignment_group_name",
        ),
        migrations.RemoveField(
            model_name="canvascourse",
            name="course_id",
        ),
        migrations.RemoveField(
            model_name="canvascourse",
            name="token",
        ),
        migrations.RemoveField(
            model_name="canvascourse",
            name="verification_assignment_group_id",
        ),
        migrations.RemoveField(
            model_name="canvascourse",
            name="verification_assignment_group_name",
        ),
        migrations.RemoveField(
            model_name="canvascourse",
            name="verification_assignment_id",
        ),
        migrations.RemoveField(
            model_name="canvascourse",
            name="verification_assignment_name",
        ),
    ]
