# Generated by Django 3.0.14 on 2022-12-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0019_auto_20221227_1316"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="canvascourse",
            name="mock",
        ),
    ]
