# Generated by Django 3.0.14 on 2022-12-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0020_remove_canvascourse_mock'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='challenge_type',
            field=models.CharField(blank=True, choices=[('QUOTA', 'QUOTA'), ('TOP_3_TEAMS', 'TOP_3_TEAMS')], max_length=500, null=True),
        ),
    ]
