# Generated by Django 3.0.14 on 2023-01-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0021_auto_20221231_1134"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
