# Generated by Django 3.0.14 on 2023-02-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0022_event_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvascourse',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
