# Generated by Django 3.0.14 on 2023-04-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0024_event_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
