# Generated by Django 3.0.14 on 2023-04-11 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0024_event_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('course', 'name')},
        ),
    ]
