# Generated by Django 3.0.14 on 2023-04-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0024_event_author'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('name', 'course'), name='course_assessment_name_unique'),
        ),
    ]
