# Generated by Django 3.0.14 on 2023-04-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0025_eventset"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="event",
            unique_together={("course", "name")},
        ),
    ]
