from .action import ActionsViewSet
from .contact_us import ContactUsViewSet
from .faq import FAQViewSet
from .multiple_choice_question import SampleMultipleChoiceQuestionViewSet
from .question import QuestionViewSet
from .question_category import QuestionCategoryViewSet
from .token_value import TokenValueViewSet
from .uqj import UQJViewSet
from .user_consent import UserConsentViewSet
from .user_stats import UserStatsViewSet
from .course import CourseViewSet
