"""
Django settings for canvas_gamification project.

Generated by 'django-admin startproject' using Django 3.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

import sentry_sdk
from corsheaders.defaults import default_headers
from django.contrib.messages import constants as message_constants
from django.urls import reverse_lazy
from sentry_sdk.integrations.django import DjangoIntegration

from canvas_gamification.csrf import trusted_origins
from canvas_gamification.env import read_env

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "true") == "true"
HEROKU = False

if DEBUG:
    read_env(os.path.join(BASE_DIR, "env", "gamification.dev.env"))

# SECURITY WARNING: keep the secret key used in production secret!
# Required from the environment in production: an unset key must stop the
# process rather than silently fall back to a value committed to this
# repository, which would be public and therefore no secret at all.
if DEBUG:
    SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-dev-key-not-for-production")
else:
    SECRET_KEY = os.environ["SECRET_KEY"]

# Whitespace-separated previous keys. Signatures made with them still verify,
# so rotating SECRET_KEY does not log everyone out or invalidate password-reset
# links that are already in flight. Drop an old key once it is older than both
# SESSION_COOKIE_AGE (14 days) and PASSWORD_RESET_TIMEOUT (3 days) -- while it
# is listed, anything signed with it is still accepted.
SECRET_KEY_FALLBACKS = os.environ.get("SECRET_KEY_FALLBACKS", "").split()

if HEROKU:
    ALLOWED_HOSTS = ["canvas-gamification.herokuapp.com"]
elif DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = os.environ["SERVER_NAME"].split()

# The app runs behind a reverse proxy that terminates TLS (see env/nginx.conf),
# so the request reaching gunicorn is plain HTTP. Trust the forwarded scheme,
# otherwise request.is_secure() is False for genuinely secure requests.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Django 4.0+ rejects unsafe-method requests whose Origin does not match the
# expected origin, which breaks admin login behind TLS termination.
CSRF_TRUSTED_ORIGINS = trusted_origins(ALLOWED_HOSTS)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "django_filters",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "accounts",
    "course",
    "general",
    "api",
    "canvas",
    "analytics",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "canvas_gamification.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "canvas_gamification.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if DEBUG:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
            "TEST": {
                "NAME": os.environ.get("TEST_DB_NAME", os.path.join(BASE_DIR, "db_test.sqlite3")),
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "postgres"),
            "USER": os.environ.get("POSTGRES_USER", "postgres"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
            "HOST": os.environ.get("POSTGRES_HOST", "db"),
            "PORT": os.environ.get("POSTGRES_PORT", 5432),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

# Canonical name for the former "Canada/Pacific" alias -- same zone, same rules.
# Debian 13 moved the legacy aliases into a separate tzdata-legacy package, and
# Django validates TIME_ZONE against /usr/share/zoneinfo at startup.
TIME_ZONE = "America/Vancouver"

USE_I18N = True

USE_TZ = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ]
}


MESSAGE_TAGS = {message_constants.ERROR: "danger"}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

AUTH_USER_MODEL = "accounts.MyUser"

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "debug.log"),
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": True,
        },
    },
}

LOGIN_URL = reverse_lazy("rest_framework:login")
LOGOUT_URL = reverse_lazy("rest_framework:logout")
LOGIN_REDIRECT_URL = reverse_lazy("api:api-root")
LOGOUT_REDIRECT_URL = reverse_lazy("api:api-root")

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_HEADERS = list(default_headers) + [
        "sentry-trace",
        "baggage",
    ]

if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    EMAIL_ACTIVATION = "test@gamification.com"
    EMAIL_PASSWORD_RESET = "test@gamification.com"
else:
    EMAIL_USE_TLS = os.environ["EMAIL_USE_TLS"]
    EMAIL_HOST = os.environ["EMAIL_HOST"]
    EMAIL_HOST_USER = os.environ["EMAIL_HOST_USER"]
    EMAIL_HOST_PASSWORD = os.environ["EMAIL_HOST_PASSWORD"]
    EMAIL_PORT = os.environ["EMAIL_PORT"]
    EMAIL_ACTIVATION = os.environ["EMAIL_ACTIVATION"]
    EMAIL_PASSWORD_RESET = os.environ["EMAIL_PASSWORD_RESET"]
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

JUDGE0_HOST = os.environ["JUDGE0_HOST"]
JUDGE0_PASSWORD = os.environ["JUDGE0_PASSWORD"]

if DEBUG:
    RECAPTCHA_KEY = ""
    RECAPTCHA_URL = ""
else:
    RECAPTCHA_KEY = os.environ["RECAPTCHA_KEY"]
    RECAPTCHA_URL = os.environ["RECAPTCHA_URL"]

if HEROKU:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

    import dj_database_url

    prod_db = dj_database_url.config(conn_max_age=500)
    DATABASES["default"].update(prod_db)

# PyJWT >= 2.10 refuses to sign with an empty HMAC key, so leaving this unset would
# make MyUser.community_jwt raise and 500 every login. Fall back to SECRET_KEY.
# Deployments that do set COMMUNITY_JWT_PRIVATE_KEY are unaffected.
COMMUNITY_JWT_PRIVATE_KEY = os.environ.get("COMMUNITY_JWT_PRIVATE_KEY", "") or SECRET_KEY

if DEBUG is False:
    sentry_sdk.init(
        dsn=os.environ["SENTRY_DSN"],
        integrations=[DjangoIntegration()],
        traces_sample_rate=0.1,
        send_default_pii=True,
    )
