# Generated by Django 3.0.3 on 2020-06-21 00:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='time_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
