# Generated by Django 3.0.7 on 2020-11-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
    ]
