# Generated by Django 3.0.7 on 2020-11-25 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20201120_1808'),
        ('general', '0005_auto_20201117_2356'),
    ]

    operations = [
    ]
