# Generated by Django 3.0.14 on 2021-10-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20210829_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unclear_description', models.BooleanField(db_index=True, default=False)),
                ('test_case_incorrect_answer', models.BooleanField(db_index=True, default=False)),
                ('test_case_violate_constraints', models.BooleanField(db_index=True, default=False)),
                ('poor_test_coverage', models.BooleanField(db_index=True, default=False)),
                ('language_specific_issue', models.BooleanField(db_index=True, default=False)),
                ('other', models.BooleanField(db_index=True, default=False)),
                ('report_text', models.TextField(db_index=True, default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='verb',
            field=models.CharField(choices=[('Created', 'Created'), ('Completed', 'Completed'), ('Opened', 'Opened'), ('Deleted', 'Deleted'), ('Delivered', 'Delivered'), ('Read', 'Read'), ('Solved', 'Solved'), ('Submitted', 'Submitted'), ('Sent', 'Sent'), ('Started', 'Started'), ('Used', 'Used'), ('Registered', 'Registered'), ('Edited', 'Edited'), ('Unread', 'Unread'), ('Skipped', 'Skipped'), ('Logged In', 'Logged In'), ('Logged Out', 'Logged Out'), ('Evaluated', 'Evaluated'), ('Updated', 'Updated')], max_length=100),
        ),
    ]
