# Generated by Django 3.0.14 on 2021-10-11 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0020_question_question_status'),
        ('general', '0007_auto_20210829_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='verb',
            field=models.CharField(choices=[('Created', 'Created'), ('Completed', 'Completed'), ('Opened', 'Opened'), ('Deleted', 'Deleted'), ('Delivered', 'Delivered'), ('Read', 'Read'), ('Solved', 'Solved'), ('Submitted', 'Submitted'), ('Sent', 'Sent'), ('Started', 'Started'), ('Used', 'Used'), ('Registered', 'Registered'), ('Edited', 'Edited'), ('Unread', 'Unread'), ('Skipped', 'Skipped'), ('Logged In', 'Logged In'), ('Logged Out', 'Logged Out'), ('Evaluated', 'Evaluated'), ('Updated', 'Updated')], max_length=100),
        ),
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_timestamp', models.DateTimeField(db_index=True, default=None, null=True)),
                ('unclear_description', models.BooleanField(db_index=True, default=False)),
                ('test_case_incorrect_answer', models.BooleanField(db_index=True, default=False)),
                ('test_case_violate_constraints', models.BooleanField(db_index=True, default=False)),
                ('poor_test_coverage', models.BooleanField(db_index=True, default=False)),
                ('language_specific_issue', models.BooleanField(db_index=True, default=False)),
                ('other', models.BooleanField(db_index=True, default=False)),
                ('report_text', models.TextField(db_index=True, default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
