# Generated by Django 3.0.14 on 2021-10-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_remove_questionreport_report_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
