# Generated by Django 3.0.14 on 2021-06-16 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canvas', '0008_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader_Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_visible', models.BooleanField(default=False)),
                ('assigned_course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='canvas.CanvasCourse')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderBoardAssignedStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_board', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leader_board.Leader_Board')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
