# Generated by Django 3.0.14 on 2021-06-15 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canvas', '0008_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader_Board',
            fields=[
                ('leaderBoardId', models.AutoField(primary_key=True, serialize=False)),
                ('courseId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_board_requests_created', to='canvas.CanvasCourse')),
                ('total_tokens_received', models.ForeignKey(on_delete=models.SET(0), to='canvas.CanvasCourse')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
