# Generated by Django 3.0.14 on 2021-06-15 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0008_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leader_board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader_board',
            name='leaderBoardId',
        ),
        migrations.AddField(
            model_name='leader_board',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leader_board',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leader_board',
            name='name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leader_board',
            name='courseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='leader_board_requests_created', to='canvas.CanvasCourse'),
        ),
        migrations.AlterField(
            model_name='leader_board',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LeaderBoardAssignedStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_board', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leader_board.Leader_Board')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
