# Generated by Django 3.0.14 on 2021-06-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0008_event_type'),
        ('leader_board', '0002_auto_20210615_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader_board',
            name='total_tokens_received',
        ),
        migrations.AddField(
            model_name='leaderboardassignedstudents',
            name='total_tokens_received',
            field=models.ForeignKey(default=1, on_delete=models.SET(0), to='canvas.CanvasCourse'),
            preserve_default=False,
        ),
    ]
