# Generated by Django 3.0.14 on 2021-06-16 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leader_board', '0003_auto_20210615_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboardassignedstudents',
            name='leader_board',
        ),
    ]
