# Generated by Django 3.0.14 on 2021-06-16 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0008_event_type'),
        ('leader_board', '0004_remove_leaderboardassignedstudents_leader_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardassignedstudents',
            name='courseId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='leaderboardassignedstudents_requests_created', to='canvas.CanvasCourse'),
            preserve_default=False,
        ),
    ]
