name: Black

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.14']

    steps:
    - uses: actions/checkout@v2
    - uses: psf/black@stable
      with:
        options: "--check"
        src: "."
        version: "26.5.1"
